version: "3.3"

services:
  postgress:
    image: postgres:13
    environment:
      - POSTGRESS_DB=my_store
      - POSTGRESS_USER=nico
      - POSTGRESS_PASSWORD=admin123
    ports:
      - 5432:5432
